# Generated by Django 4.0.6 on 2022-07-15 11:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Loan', 'Treasury'), ('Grant Aid', 'Grant Aid')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Treasury', 'Treasury'), ('Bank Loan', 'Bank Loan')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('aid_amount_etb', models.IntegerField()),
                ('aid_amount_usd', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_amount_etb', models.IntegerField()),
                ('loan_amount_usd', models.IntegerField()),
                ('loan_duration', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jointly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('inland_share_etb', models.IntegerField()),
                ('abroad_share_etb', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='loaderOrAiders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_outcome', models.TextField()),
                ('project_regions', models.CharField(blank=True, choices=[('one region', 'one region'), ('adjacent region', 'adjacent region')], default='active', max_length=400)),
                ('project_duration', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIntendedBeneficiaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_beneficiaries', models.TextField(max_length=500)),
                ('indirect_beneficiaries', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('ministry_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('main_department_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('owner_office_place', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSupervisingSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.region')),
            ],
        ),
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSourceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.abroad')),
                ('domestic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.domestic')),
                ('external_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.externalaid')),
                ('external_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.externalloan')),
                ('jointly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.jointly')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.region')),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.woreda')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.zone')),
            ],
        ),
        migrations.CreateModel(
            name='projectImplementationAndPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date_of_plane_for_evaluation_pdm', models.DateTimeField()),
                ('reason', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.result')),
                ('project_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.projectappraisal')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_cost_etb', models.IntegerField()),
                ('investment_cost_usd', models.IntegerField()),
                ('project_finance_source', models.CharField(choices=[('Domestic', 'Domestic'), ('Abroad', 'Abroad'), ('Domestic & Abroad', 'Domestic & Abroad')], max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_source_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.projectsourcedetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAppraisalEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date_of_project_appraisal_to_pds', models.DateTimeField()),
                ('reason', models.TextField()),
                ('date_of_appraisal_result_sent', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appraisal_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.result')),
                ('project_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.projectappraisal')),
            ],
        ),
        migrations.AddField(
            model_name='projectappraisal',
            name='project_finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='project_Appriasal.projectfinance'),
        ),
        migrations.AddField(
            model_name='projectappraisal',
            name='project_intended_beneficiaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_intended_beneficiaries', to='project_Appriasal.projectintendedbeneficiaries'),
        ),
        migrations.AddField(
            model_name='projectappraisal',
            name='project_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='project_Appriasal.projectsite'),
        ),
        migrations.AddField(
            model_name='projectappraisal',
            name='project_supervising_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='project_Appriasal.projectowner'),
        ),
        migrations.AddField(
            model_name='jointly',
            name='name_of_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.loaderoraiders'),
        ),
        migrations.AddField(
            model_name='externalloan',
            name='loaner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.loaderoraiders'),
        ),
        migrations.AddField(
            model_name='externalaid',
            name='aider_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.loaderoraiders'),
        ),
    ]
