# Generated by Django 4.0.6 on 2022-07-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_Appriasal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectappraisal',
            name='project_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='project_Appriasal.projectowner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectappraisal',
            name='project_finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_finance', to='project_Appriasal.projectfinance'),
        ),
        migrations.AlterField(
            model_name='projectappraisal',
            name='project_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_site', to='project_Appriasal.projectsite'),
        ),
        migrations.AlterField(
            model_name='projectappraisal',
            name='project_supervising_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evaluation_sector', to='project_Appriasal.projectsupervisingsector'),
        ),
    ]
