# Generated by Django 4.0.6 on 2022-07-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_Appriasal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_b_year_financial_performance_birr', models.IntegerField(help_text="previous budget years's financial performance in million Birr")),
                ('budget_financial_plan', models.IntegerField(help_text=" budget years's financial plan")),
                ('quarter_plan', models.IntegerField(help_text='Quarter plan')),
                ('YTD_financial_work_plan', models.IntegerField(help_text='money allocated for the project until the budget year')),
                ('YTD_financial_work_performance', models.IntegerField(help_text='Total money used until now')),
                ('YTD_financial_performance_to_plan_ratio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('si_unit', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year_obstacle', models.TextField()),
                ('project_total_limitation', models.TextField()),
                ('project_comment', models.TextField()),
                ('project_file', models.ImageField(blank=True, null=True, upload_to='project_file/')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterFinancialPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.IntegerField(help_text='quarter year performance  ')),
                ('second_quarter', models.IntegerField(help_text='quarter year performance ')),
                ('third_quarter', models.IntegerField(help_text='quarter year performance  ')),
                ('fourth_quarter', models.IntegerField(help_text='quarter year performance ')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterFinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.IntegerField(help_text='quarter year plan ')),
                ('second_quarter', models.IntegerField(help_text='quarter year plan ')),
                ('third_quarter', models.IntegerField(help_text='quarter year plan ')),
                ('fourth_quarter', models.IntegerField(help_text='quarter year plan ')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterFinancialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.IntegerField(help_text='quarter year performance  ')),
                ('second_quarter', models.IntegerField(help_text='quarter year performance ')),
                ('third_quarter', models.IntegerField(help_text='quarter year performance  ')),
                ('fourth_quarter', models.IntegerField(help_text='quarter year performance ')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterWorkPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('second_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('third_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('fourth_quarter', models.IntegerField(help_text='quarter year plan  in %')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_budget_year', models.DateField(help_text='budget year')),
                ('pre_b_year_work_perf_in_percent', models.IntegerField(help_text='budget year financial performance in %')),
                ('physical_work_plan_year', models.IntegerField(help_text="short description of the BUdget year's plan in %")),
                ('project_work_performance_quarter', models.IntegerField(help_text='Numerical description of the quarter year performance')),
                ('project_performance_to_plan_ratio', models.IntegerField(help_text='Performance to plan ratio')),
                ('YTD_physical_work_plan', models.IntegerField(help_text='project total physical plan')),
                ('YTD_physical_work_performance', models.ImageField(help_text='YTD physical work performance', upload_to='')),
                ('YTD_performance_to_plan_ratio', models.IntegerField(help_text='total physical work performance to plan ratio')),
                ('project_work_pane_in_four_quarter', models.ForeignKey(help_text="short description of the quarter year's plan in number", on_delete=django.db.models.deletion.CASCADE, to='project_implementation.quarterworkplane')),
                ('work_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.workstatustype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImplementations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_starting_date', models.DateTimeField()),
                ('project_ending_date', models.DateTimeField()),
                ('consultant_advisor_name', models.CharField(max_length=100)),
                ('contractor_name', models.CharField(max_length=100)),
                ('measurement_value', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_Appriasal.projectappraisal')),
                ('project_consultant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_consultant_type', to='project_implementation.consultanttype')),
                ('project_contractor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contractor_type', to='project_implementation.consultanttype')),
                ('project_financial_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.financialstatus')),
                ('project_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.measurement')),
                ('project_remark', models.ManyToManyField(to='project_implementation.projectremark')),
                ('project_work_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.projectworkstatus')),
            ],
        ),
        migrations.AddField(
            model_name='financialstatus',
            name='quarter_financial_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.quarterfinancialperformance'),
        ),
        migrations.AddField(
            model_name='financialstatus',
            name='quarter_financial_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.quarterfinancialplan'),
        ),
        migrations.AddField(
            model_name='financialstatus',
            name='quarter_financial_ratio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.quarterfinancialratio'),
        ),
    ]
