# Generated by Django 4.0.6 on 2022-07-25 07:34

from django.db import migrations, models
import project_implementation.models.project_implementations


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterWorkPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('second_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('third_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('fourth_quarter', models.IntegerField(help_text='quarter year plan  in %')),
            ],
        ),
        migrations.AlterField(
            model_name='projectworkstatus',
            name='YTD_physical_work_performance',
            field=models.IntegerField(help_text='YTD physical work performance'),
        ),
        migrations.AlterField(
            model_name='projectworkstatus',
            name='project_work_performance_quarter',
            field=models.IntegerField(help_text='Numerical description of the quarter year performance', verbose_name=project_implementation.models.project_implementations.QuarterWorkPerformance),
        ),
    ]
