# Generated by Django 4.0.6 on 2022-07-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0002_quarterworkperformance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkstatus',
            name='project_work_performance_quarter',
            field=models.ForeignKey(help_text='Numerical description of the quarter year performance', on_delete=django.db.models.deletion.CASCADE, to='project_implementation.quarterworkperformance'),
        ),
    ]
