# Generated by Django 4.0.6 on 2022-08-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0003_alter_projectworkstatus_project_work_performance_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImplementationsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(null=True, upload_to='project_implementations_image')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('project_finance_source', models.CharField(choices=[('First', 'First'), ('second', 'Second'), ('Third', 'Third'), ('Forth', 'Forth')], max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_implementation.projectimplementations')),
            ],
        ),
    ]
