# Generated by Django 4.0.6 on 2022-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0004_projectimplementationsmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimplementationsmedia',
            old_name='project_finance_source',
            new_name='quarter',
        ),
        migrations.AddField(
            model_name='projectimplementationsmedia',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
