# Generated by Django 4.0.6 on 2022-08-10 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_implementation', '0006_projectimplementationsmedia_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterWorkPerformanceToPlanRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('second_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('third_quarter', models.IntegerField(help_text='quarter year plan  in %')),
                ('fourth_quarter', models.IntegerField(help_text='quarter year plan  in %')),
            ],
        ),
        migrations.AlterField(
            model_name='projectworkstatus',
            name='project_performance_to_plan_ratio',
            field=models.ForeignKey(help_text='Numerical description of the quarter year performance to plan Ratio', on_delete=django.db.models.deletion.CASCADE, to='project_implementation.quarterworkperformancetoplanratio'),
        ),
    ]
